/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author root
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTelaDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ferramentasTodas = new javax.swing.JMenuItem();
        ferramentasEmprestadas = new javax.swing.JMenuItem();
        ferramentasDisponiveis = new javax.swing.JMenuItem();
        ferramentasCadastrar = new javax.swing.JMenuItem();
        ferramentasEditar = new javax.swing.JMenuItem();
        ferramentasExcluir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        amigosTodos = new javax.swing.JMenuItem();
        amigosEmprestados = new javax.swing.JMenuItem();
        amigosDevedores = new javax.swing.JMenuItem();
        amigosCadastrar = new javax.swing.JMenuItem();
        amigosEditar = new javax.swing.JMenuItem();
        amigosExcluir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        negociosEmprestar = new javax.swing.JMenuItem();
        amigosDevolver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de ferramentas");

        jTelaDesktop.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jTelaDesktopLayout = new javax.swing.GroupLayout(jTelaDesktop);
        jTelaDesktop.setLayout(jTelaDesktopLayout);
        jTelaDesktopLayout.setHorizontalGroup(
            jTelaDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        jTelaDesktopLayout.setVerticalGroup(
            jTelaDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));

        jMenu1.setText("Ferramentas");

        ferramentasTodas.setText("Listar todas");
        ferramentasTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ferramentasTodasActionPerformed(evt);
            }
        });
        jMenu1.add(ferramentasTodas);

        ferramentasEmprestadas.setText("Listar emprestadas");
        jMenu1.add(ferramentasEmprestadas);

        ferramentasDisponiveis.setText("Listar disponíveis");
        jMenu1.add(ferramentasDisponiveis);

        ferramentasCadastrar.setText("Cadastrar");
        ferramentasCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ferramentasCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(ferramentasCadastrar);

        ferramentasEditar.setText("Editar");
        jMenu1.add(ferramentasEditar);

        ferramentasExcluir.setText("Excluir");
        jMenu1.add(ferramentasExcluir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Amigos");

        amigosTodos.setText("Listar todos");
        jMenu2.add(amigosTodos);

        amigosEmprestados.setText("Listar emprestados");
        jMenu2.add(amigosEmprestados);

        amigosDevedores.setText("Listar devedores");
        jMenu2.add(amigosDevedores);

        amigosCadastrar.setText("Cadastrar");
        amigosCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amigosCadastrarActionPerformed(evt);
            }
        });
        jMenu2.add(amigosCadastrar);

        amigosEditar.setText("Editar");
        jMenu2.add(amigosEditar);

        amigosExcluir.setText("Excluir");
        jMenu2.add(amigosExcluir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Negócios");

        negociosEmprestar.setText("Emprestar");
        negociosEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negociosEmprestarActionPerformed(evt);
            }
        });
        jMenu3.add(negociosEmprestar);

        amigosDevolver.setText("Devolver");
        amigosDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amigosDevolverActionPerformed(evt);
            }
        });
        jMenu3.add(amigosDevolver);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ferramentasTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ferramentasTodasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ferramentasTodasActionPerformed

    private void ferramentasCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ferramentasCadastrarActionPerformed
        TelaCadastroFerramentaV2 telaCadastroFerramenta = new TelaCadastroFerramentaV2();
        jTelaDesktop.add(telaCadastroFerramenta);
        telaCadastroFerramenta.setVisible(true);
    }//GEN-LAST:event_ferramentasCadastrarActionPerformed

    private void amigosCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amigosCadastrarActionPerformed
        TelaCadastroAmigoV2 telaCadastroAmigo = new TelaCadastroAmigoV2();
        jTelaDesktop.add(telaCadastroAmigo);
        telaCadastroAmigo.setVisible(true);
    }//GEN-LAST:event_amigosCadastrarActionPerformed

    private void negociosEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negociosEmprestarActionPerformed
        // TODO add your handling code here:
        TelaEmprestarFerramenta objeto = new TelaEmprestarFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_negociosEmprestarActionPerformed

    private void amigosDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amigosDevolverActionPerformed
        // TODO add your handling code here:
        TelaDevolverFerramenta objeto = new TelaDevolverFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_amigosDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem amigosCadastrar;
    private javax.swing.JMenuItem amigosDevedores;
    private javax.swing.JMenuItem amigosDevolver;
    private javax.swing.JMenuItem amigosEditar;
    private javax.swing.JMenuItem amigosEmprestados;
    private javax.swing.JMenuItem amigosExcluir;
    private javax.swing.JMenuItem amigosTodos;
    private javax.swing.JMenuItem ferramentasCadastrar;
    private javax.swing.JMenuItem ferramentasDisponiveis;
    private javax.swing.JMenuItem ferramentasEditar;
    private javax.swing.JMenuItem ferramentasEmprestadas;
    private javax.swing.JMenuItem ferramentasExcluir;
    private javax.swing.JMenuItem ferramentasTodas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jTelaDesktop;
    private javax.swing.JMenuItem negociosEmprestar;
    // End of variables declaration//GEN-END:variables
}
