/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author joaoi
 */
public class PainelFerramenta extends javax.swing.JFrame {

    /**
     * Creates new form PainelFerramenta
     */
    public PainelFerramenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOkFerramenta = new javax.swing.JButton();
        jFecharFerramenta = new javax.swing.JButton();
        jTituloFerramenta = new javax.swing.JLabel();
        jNomeFerramenta = new javax.swing.JLabel();
        jDigiteFerramenta = new javax.swing.JTextField();
        jMarca = new javax.swing.JLabel();
        jDigiteMarca = new javax.swing.JTextField();
        jValor = new javax.swing.JLabel();
        jDigiteValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jOkFerramenta.setText("OK");

        jFecharFerramenta.setText("Fechar");
        jFecharFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFecharFerramentaActionPerformed(evt);
            }
        });

        jTituloFerramenta.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jTituloFerramenta.setText("FERRAMENTA");

        jNomeFerramenta.setText("Nome");

        jDigiteFerramenta.setText("Digite o nome");
        jDigiteFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDigiteFerramentaActionPerformed(evt);
            }
        });

        jMarca.setText("Marca");

        jDigiteMarca.setText("Digite a marca");

        jValor.setText("Valor");

        jDigiteValor.setText("Digite o valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jOkFerramenta)
                        .addGap(56, 56, 56)
                        .addComponent(jFecharFerramenta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNomeFerramenta)
                            .addComponent(jTituloFerramenta)
                            .addComponent(jMarca)
                            .addComponent(jValor)
                            .addComponent(jDigiteValor)
                            .addComponent(jDigiteMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(jDigiteFerramenta))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTituloFerramenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jNomeFerramenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDigiteFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDigiteMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDigiteValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOkFerramenta)
                    .addComponent(jFecharFerramenta))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDigiteFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDigiteFerramentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDigiteFerramentaActionPerformed

    private void jFecharFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFecharFerramentaActionPerformed
System.exit(0);         // TODO add your handling code here:
    }//GEN-LAST:event_jFecharFerramentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PainelFerramenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jDigiteFerramenta;
    private javax.swing.JTextField jDigiteMarca;
    private javax.swing.JTextField jDigiteValor;
    private javax.swing.JButton jFecharFerramenta;
    private javax.swing.JLabel jMarca;
    private javax.swing.JLabel jNomeFerramenta;
    private javax.swing.JButton jOkFerramenta;
    private javax.swing.JLabel jTituloFerramenta;
    private javax.swing.JLabel jValor;
    // End of variables declaration//GEN-END:variables
}
